name: Documentation

on:
  push:
    branches:
      - main
      - master
      - release/**
  pull_request:
    branches:
      - main
      - master
      - release/**

jobs:
  sphinx:
    # -----------------------
    # Generate the documentation
    # -----------------------
    name: Sphinx

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements
      run: python -m pip install -r requirements.txt

    - name: Install LIGOTimeGPS
      run: python -m pip install .

    - name: Package list
      run: python -m pip list installed

    - name: Build documentation
      run: python -m sphinx -b html -W -v --color docs/ _build/

    - name: Upload documentation build
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: _build
